### ISSUE TITLE
[BUG] Waypoint lines get cut out on the minimap

### ISSUE THREAD

**Issue by mikeeyhz** [qbcore-framework/qb-hud#100]
**Describe the bug**
Waypoint lines get cut out on the minimap when the route-line falls outside of "invisible rectangle"

**To Reproduce**

This is going to look like a no-effort report, but there really are no steps to reproduce. The issue occurs on default settings, default resources. 

**Expected behavior**
Expected behaviour would be for the waypoint line to go across the whole minimap

**Screenshots**

https://cdn.discordapp.com/attachments/929226960951975986/933016167713493042/unknown.png

https://cdn.discordapp.com/attachments/929226960951975986/933015756092891166/unknown.png

https://cdn.discordapp.com/attachments/929226960951975986/933015334070419466/unknown.png

https://cdn.discordapp.com/attachments/929226960951975986/933014025527255050/unknown.png

**Questions (please complete the following information):**
 - When you last updated: Today, most recent and 5 days ago
 - Are you using custom resource? n/a
 - Have you renamed `qb-` to something custom? no

**Comment by BlueSky-fur** [comment]
im honestly not even sure if thats possible, i noticed when playing on NoPixel that even they have the issue and cant seem to fix it i guess thats just something you have to live with if you modify the minimap

**Comment by loljoshie** [comment]
Square should now be fixed however circle still needs more adjustments which I'll hopefully get around to soon. Thanks for reporting!
