### ISSUE TITLE
Harness Callback Issue [BUG]

### ISSUE THREAD

**Issue by Scott1sh** [qbcore-framework/qb-hud#101]
The client.lua has a harness cb but it seems to be missing from the server.lua

The old lj-hud had the server callback. Tested this on our dev server and it shows the harness icon (when having a harness inside your inventory)

QBCore.Functions.CreateCallback('hud:server:HasHarness', function(source, cb)
    local source = source
    local Ply = QBCore.Functions.GetPlayer(source)
    local Harness = Ply.Functions.GetItemByName("harness")
    if Harness ~= nil then
        cb(true)
    else
        cb(false)
    end
end)

![5HXuT](https://user-images.githubusercontent.com/8031389/150050335-89583ea5-432b-4c10-a328-250c71648711.png)

**Comment by loljoshie** [comment]
Should be fixed with the latest PR Berkie did! Thanks!
