### ISSUE TITLE
[BUG] Tunerchip freezes HUD

### ISSUE THREAD

**Issue by JesusShaves** [qbcore-framework/qb-hud#110]
**Describe the bug**
Using the QB-TUNERCHIP tends to freeze the HUD, as does using any of the drugs from case-codes. (OG Kush, White Widow, Purple haze, etc)

**To Reproduce**
1. Get in a vehicle, open inventory, use tunerchip.
2. Sometimes the UI for the Tuner won't appear on screen, and you have to hit ESC to back out.
***When attempting to use drugs, it tells you that you don't have a lighter, even if you do, all results are the same with the tuner.
3. The HUD freezes, values do not update, and the resethud doesn't clear it up, only restarting the resource qb-hud.
4. There are no errors in Server Console or F8 shown.

**Expected behavior**
When using a tuner, the UI should appear, allow you to apply a tune and close the UI.

**Screenshots**
https://gyazo.com/72fd31dc729490072e8a569ccf97c168

**Questions (please complete the following information):**
 - When you last updated: 1/20/2022
 - Are you using custom resource? case-outdoorweed, case-meth, case-coke - Tuner is default QB
 - Have you renamed `qb-` to something custom? No

**Additional context**
replay link: https://www.youtube.com/watch?v=W9EfFl4iFeE

**Comment by YazIV** [comment]
I can back him on that

**Comment by ItsAegeus** [comment]
Can confirm this is a bug thats going around.

**Comment by MonkeyWhisper** [comment]
Does not occur to me, on a fresh copy.

**Comment by loljoshie** [comment]
Thanks Monkey, reopen this issue if problems persist.
