### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by balcer64** [qbcore-framework/qb-hud#111]
everything is visible on the screenshots. while in the car, the minimap and route are shifted
![screenshot103](https://user-images.githubusercontent.com/22128071/150635449-f19c0cc8-c1d1-4db9-85c6-f40f8327d7f3.png)
![screenshot104](https://user-images.githubusercontent.com/22128071/150635450-a9ec9a61-1761-4634-b8f3-9ac8a3768c76.png)

**Comment by tony-stark-17** [comment]
Try settings and change the safezone size
