### ISSUE TITLE
[BUG] Map is always square and squashed on load in

### ISSUE THREAD

**Issue by Smorj** [qbcore-framework/qb-hud#113]
When players load in the minimap when in a vehicle is always square not a rectangle or a circle and you have to cycle between the circle and square options to properly set it every log in.

https://i.imgur.com/T0XNkkx.png

Have tried fresh installs of latest versions, still the same. no errors or anything.

**Comment by jnccloud** [comment]
This looks like it's because you've replaced the streamed files in the hud. You need to make sure to use the correct YTDs to fit the map into the HUD correctly. The base package only includes a black and grey map without streetnames.

**Comment by Smorj** [comment]
> This looks like it's because you've replaced the streamed files in the hud. You need to make sure to use the correct YTDs to fit the map into the HUD correctly. The base package only includes a black and grey map without streetnames.

It was happening before I added a streamed map, and it still happens with a fresh install too.

**Comment by MonkeyWhisper** [comment]
I tested myself and had a few others, cannot duplicate this problem. Does this happen to every single player of yours?

> When players load in the minimap when in a vehicle is always square not a rectangle or a circle and you have to cycle between the circle and square options to properly set it every log in.
> 
> https://i.imgur.com/T0XNkkx.png
> 
> Have tried fresh installs of latest versions, still the same. no errors or anything.

**Comment by Smorj** [comment]
> I tested myself and had a few others, cannot duplicate this problem. Does this happen to every single player of yours?
> 
> > When players load in the minimap when in a vehicle is always square not a rectangle or a circle and you have to cycle between the circle and square options to properly set it every log in.
> > https://i.imgur.com/T0XNkkx.png
> > Have tried fresh installs of latest versions, still the same. no errors or anything.

It's not every player but it's most people.

**Comment by akshaynstack** [comment]
It’s not fixed, can you guide me how to fix it, the minimap is square
