### ISSUE TITLE
[BUG] Compass still shows during cinematic

### ISSUE THREAD

**Issue by Boom1053** [qbcore-framework/qb-hud#115]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

I click cinematic mode and compass stays on screen.

**To Reproduce**
1. Go to '...' /menu
2. Click on '....' cinematic mode
3. Use this item '....' (item's name from shared.lua if applicable)

**Expected behavior**
A clear and concise description of what you expected to happen. - compass be removed like the rest of the hud?

**Screenshots**
If applicable, add screenshots to help explain your problem. - https://yourehella.gay/⁠‍‍‌‍‍⁠⁠‌⁠​‍⁠‌​‌‌⁠⁠⁠

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] 540 am eastern timezone 1/25/2022
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] a few like the ones named.
 - Have you renamed `qb-` to something custom? [e.g. yes/no] no

**Additional context**

**Comment by ItsANoBrainer** [comment]
This seems to have been addressed with the latest rework. If you are still having problems update to the latest core and hud.
