### ISSUE TITLE
Hud disappears when i connect to server. Resetting hud settings, is the only work around and reconnect to server.

### ISSUE THREAD

**Issue by Maxithx666** [qbcore-framework/qb-hud#121]
Hud disappears when i connect to server. Resetting hud settings, is the only work around and reconnecting to server after Hud is beeing reset.

**To Reproduce**
1. login to server and no hud i showing up
2. Then i try to reset HUD. it just appears shotly and goes away again
3. If i then reset hud setting and then disconnect and connect again, then hud works again.
4. If i then disconnect from server and reconnect again. no hud again. until i reset hud settings.

**Expected behavior**
I guess the Hud should always be there when i connect to server, or if i disconnect/reconnect
 Without the need for resetting hud all the time.

**Setting in Hud menu press I
Option: Show Minimap Only in vehicle = disable
Status: Show Health always
Status: Show Armor always

but i guess when setting is reset my setting wont matter anyway.

** Lasters update of qb-hud is installed today

Thanks 
Maxithx666

**Comment by loljoshie** [comment]
Make sure you are fully quitting/restarting your FiveM Client every time you join the server; otherwise like what you are reporting; the HUD values will not update and will not show in general.

**Comment by Maxithx666** [comment]
thank you so much :) for info
