### ISSUE TITLE
[BUG] Weapon equipped radial

### ISSUE THREAD

**Issue by maguhd** [qbcore-framework/qb-hud#123]
**Describe the bug**
Whenever I use any emote that uses a scenario I get the weapon equipped radial and If i stop the animation, the radial gets stuck on screen until I equip and unequip a real weapon,

**To Reproduce**
1. /e smoke
**Expected behavior**
Not show that radial

**Screenshots**
![image](https://user-images.githubusercontent.com/54622859/153753654-5cfba839-0491-4c2f-a775-05eb229302ab.png)

**Questions (please complete the following information):**
 - When you last updated: I use the latest version

**Comment by ItsANoBrainer** [comment]
Can't reproduce. Please provide a video using the latest core and hud if you are still having this problem.

**Comment by shhada** [comment]
same issue here. can be reproduced by smoking a joint
