### ISSUE TITLE
[BUG] Cruise seatbelt:client:ToggleCruise

### ISSUE THREAD

**Issue by milotiro95** [qbcore-framework/qb-hud#128]
**Describe the bug**
My cruise control doesn't work. 

**To Reproduce**
1. Go on a car
2. Try to use the key Y to activate cruise
3. A message telling us the cruise is activate with et MPH but the car is not working.

**Expected behavior**
I don't know if it's on me but it's impossible to have the cruiser working

**Questions (please complete the following information):**
 - When you last updated: [e.g. 3 weeks but did some pull request]
 - Are you using custom resource? which ones? qb-target, qb-core dev branch
 - Have you renamed `qb-` to something custom? nop

**Comment by TapFreee** [comment]
can you help me with something

**Comment by Botman64** [comment]
this issue would be with small resources and i am unable to recreate
