### ISSUE TITLE
[SUGGESTION] Ability to hide HUD

### ISSUE THREAD

**Issue by Hiype** [qbcore-framework/qb-hud#138]
**Is your feature request related to a problem? Please describe.**
My idea was to create a simple screenshot script with no HUD elements, but there is no way to hide the qb-hud.

**Describe the feature you'd like**
A simple export or a net event would be amazing to hide/un-hide a HUD or a toggle would be fine too.

**Describe alternatives you've considered**
I have considered using cinematic mode or stopping hud resource overall, but these are alternatives that don't really work.

**Comment by kasper-dev** [comment]
Agreed.

**Comment by flowdgodx** [comment]
Hi! Actually there is a way. If you press the menu key ( Config.OpenMenu = 'I' ) you can turn on cinematic and the hud will hide.

**Comment by Hiype** [comment]
Yes, but its very manual and should be at least made possible using exports or triggers. Also it doesnt exactly hide the UI, it just puts on some black bars and disables the UI.
