### ISSUE TITLE
[BUG] My engine status don't go away when im off the vehicle

### ISSUE THREAD

**Issue by ghost** [qbcore-framework/qb-hud#140]
When i am off the vehicle, the engine health icon dosen't go away

![image](https://user-images.githubusercontent.com/49962755/168472490-8bd25128-b31c-4a8f-a7bb-6fa07150cb4d.png)

**Comment by Andyauk** [comment]
> When i am off the vehicle, the engine health icon dosen't go away
> 
> ![image](https://user-images.githubusercontent.com/49962755/168472490-8bd25128-b31c-4a8f-a7bb-6fa07150cb4d.png)

yes I've noticed that too with the update.

**Comment by milotiro95** [comment]
Same until the last update !

**Comment by zWyzzzzz** [comment]
i have same issue and i fix it with this pr https://github.com/qbcore-framework/qb-hud/pull/142

**Comment by FjamZoo** [comment]
This issue has now been fixed thank you for reporting it to us.
