### ISSUE TITLE
[BUG] - high MS.

### ISSUE THREAD

**Issue by LielR** [qbcore-framework/qb-hud#144]
After checking in in resmon
QB-HUD script is taking high ms..
around 0.07 and while driving it jumps to 0.10
Any ideas how to solve it?

**Comment by xenfovn** [comment]
recomment u using ubuntu 20.04 + dedicated server

**Comment by Botman64** [comment]
Inside the vehicle the resource is bound to run harder since the refresh must be faster so the speedometer can keep up as for outside the vehicle i will start looking for what optimizations i can provide because .07 is too high for my liking as well
