### ISSUE TITLE
[SUGGESTION] More Stress Configs

### ISSUE THREAD

**Issue by nzkfc** [qbcore-framework/qb-hud#151]
**Is your feature request related to a problem? Please describe.**
Stress can be fun, but at the moment it's either off or on. It would be grea to have more configs.

**Describe the feature you'd like**
Config options to:
1. Turn off stress on/off
2. Turn off stress for certain vehicles types/classes e.g. Heli, Plane, Boat etc
3. Turn off stress for any listed jobs
4. Turn off stress for any particular vehicles name

**Describe alternatives you've considered**
Custom coding in certain vehicles and such at their respective spawn function.

**Comment by GhzGarage** [comment]
Done
