### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DNDdjay** [qbcore-framework/qb-hud#153]
**Describe the bug**
females dont have fully health i know how to fix it on esx but not on qb

in esx i have too use this 

Citizen.CreateThread(function()
    while true do
        Citizen.Wait(1)
				if GetEntityMaxHealth(GetPlayerPed(-1)) ~= 200 then
			SetEntityMaxHealth(GetPlayerPed(-1), 200)
			SetEntityHealth(GetPlayerPed(-1), 200)
		end

but its is not working in qb

![IMG_20220711_074335](https://user-images.githubusercontent.com/18598238/178196837-52b97268-6b06-4a59-a9e1-4a4b202f4220.jpg)

**Comment by AlluerDuke** [comment]
the same

**Comment by Jamie9192** [comment]
try:
CreateThread(function()
    maxHealth = GetEntityMaxHealth(PlayerPedId())
    SetEntityHealth(PlayerPedId(), maxHealth)
end

untested, but im sure that should work

**Comment by dollar-src** [comment]
> Citizen.CreateThread(function()
>     while true do
>     Citizen.Wait(1)
>     if GetEntityMaxHealth(GetPlayerPed(-1)) ~= 200 then
>     SetEntityMaxHealth(GetPlayerPed(-1), 200)
>     SetEntityHealth(GetPlayerPed(-1), 200)
>     end
> end
> end)
> it works probably

**Comment by DNDdjay** [comment]
> > Citizen.CreateThread(function()
> > while true do
> > Citizen.Wait(1)
> > if GetEntityMaxHealth(GetPlayerPed(-1)) ~= 200 then
> > SetEntityMaxHealth(GetPlayerPed(-1), 200)
> > SetEntityHealth(GetPlayerPed(-1), 200)
> > end
> > end
> > end)
> > it works probably

thx its working now

**Comment by dollar-src** [comment]
no problem
