### ISSUE TITLE
[BUG] "Show Minimap Only in Vehicle" box checked has the opposite effect in qb menu

### ISSUE THREAD

**Issue by shhada** [qbcore-framework/qb-hud#157]
**Describe the bug**
in the hud's menu (/menu), the option to "Show Minimap Only in Vehicle" shows the hud when you're not in your vehicle.

**Expected behavior**
it's supposed to have the exact opposite effect while the box is checked

**Screenshots**
![FiveM_b2372_GTAProcess_uNh7dPAcRL](https://user-images.githubusercontent.com/4439191/185246990-2973d55b-197b-4d82-b4c5-b8d0785be09e.png)

**Questions (please complete the following information):**
 - When you last updated: today
 - Are you using custom resource? which ones? nope, all qbcore
 - Have you renamed `qb-` to something custom? no

**Additional context**
there should be a small fix for this, but i haven't been able to figure out how to do it

**Comment by Bongmasta406** [comment]
seems without anything modifications or anything but the most recent fresh install, From what I can tell the the qb-hud works as intended.
