### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by XeroxTEMPA** [qbcore-framework/qb-hud#168]
### Summary

Hud Not Showing

### Reproduction

1. Start server
2. Load in to server and chose character
3. Hud doesnt appear on screen 

### Expected behavior

Hud to appear

### Actual behavior

Hud doesnt appear

### Additional context

![FiveM_b2699_GTAProcess_6De3Yqhnm4](https://user-images.githubusercontent.com/88088425/192809969-90a79052-448c-47f6-866b-1d8cc7f1428f.png)

I have everything set to always show as i thought that may fix it but it didn't i removed all recently added resources and that also did not fix the issue and i did use the reset Hud option on the menu. There are no errors in F8 or TxAdmin Console.

I did rename all my resources to arp-, but it was all working after that it broke yesterday.

### Last Updated

Yesterday

### Custom Resources

no

### Resource Rename

arp

**Comment by AkselGlyholt** [comment]
I have the same problem. Did you ever find a fix for this?

**Comment by Bakisito** [comment]
i just used the command on a fresh qbcore, everything fine. no problems.
