### ISSUE TITLE
[BUG] Minimap is blank

### ISSUE THREAD

**Issue by Brantlab** [qbcore-framework/qb-hud#177]
### Summary

Minimap is blank

### Reproduction

1. started happening couple months ago. 
2. Have tried completely removing fivem and clearing cache. 
3. Issue persists.
4. only one on the server that it has happened to.

### Expected behavior

Map to load

### Actual behavior

![image](https://user-images.githubusercontent.com/36959959/214199190-41f17537-2148-4067-a46e-c62a0a90d376.png)

### Last Updated

3.2.8

### Custom Resources

unknown

### Resource Rename

No

**Comment by Bakisito** [comment]
Just install a fresh qbcore, and everything fine, 👍🏻

**Comment by promiiss033** [comment]
> Just install a fresh qbcore, and everything fine, 👍🏻

your funny
