### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TamerWaves** [qbcore-framework/qb-hud#179]
### Summary

I have no HUD or hunger, stress, etc. icons. Brand new server install

### Reproduction

Nothing, but when I reset hud it pops up for 1 second and then disappears.

### Expected behavior

To have a HUD

### Actual behavior

nada

### Additional context

Nothing

### Last Updated

today

### Custom Resources

nope

### Resource Rename

nope

**Comment by tom-osborne** [comment]
enable onesync in txadmin
