### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Sylvernl88** [qbcore-framework/qb-hud#184]
### Summary

When you use the command /resethud you get a script error 

### Reproduction

![image](https://user-images.githubusercontent.com/81586511/227578527-ce27fef6-71e5-4a6a-bb0d-fb8bfc50dff9.png)

### Expected behavior

hud reseting

### Actual behavior

Hud is crashing

### Last Updated

today

### Custom Resources

qb-target

### Resource Rename

Nope

**Comment by Bakisito** [comment]
i just used the command on a fresh qbcore, everything fine. no problems.

**Comment by GhzGarage** [comment]
Fixed
