### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lakewoodrp** [qbcore-framework/qb-hud#195]
### Summary

The new update stopped showing the hud settings with the "I" Button.

### Reproduction

Downloaded the new update

### Expected behavior

New update

### Actual behavior

The i button doesn't pop the settings for the Hud Settings.

### Additional context

Is there a way you can make it were we can true/ false all the food, water, stress, oxygen in the script just in case we don't actually want to have that.

### Last Updated

today

### Custom Resources

qbcore

### Resource Rename

no

**Comment by GhzGarage** [comment]
Check your fivem keybinds for qb-hud
