### ISSUE TITLE
Missing DLC Blips b2189 b2372

### ISSUE THREAD

**Issue by DmACKGL** [qbcore-framework/qb-hud#37]
**Describe the bug**
Blips missing/overwritten by  the streamed file `minimap.gfx` 

**To Reproduce**
1. Start qb-hud (not connected to the server)
2. Join the server
3. See the error on blips added on b2189 & b2372 (example: 740, 360, 780, 777)
4. Disconnect
5. stop qb-hud
6. Join the server
7. All works

**Expected behavior**
Blips added on b2189 & b2372 should be visible.

**Server Info:**
- Server Version: 4478
- Client Version: canary
- Client Build: b2372

**Comment by BerkieBb** [comment]
This was fixed with the minimap.gfx update
