### ISSUE TITLE
HUD not reflecting correct seatbelt status

### ISSUE THREAD

**Issue by hellogoldfish** [qbcore-framework/qb-hud#38]
If you get out of a car while also taking off the seatbelt, the HUD will display opposite of what is true when reentering the car. Like green when the seatbelt is off, and red when the seatbelt is on.

**Comment by GhzGarage** [comment]
You can’t get out while seatbelt is on

**Comment by hellogoldfish** [comment]
> You can’t get out while seatbelt is on

Sorry I phrased it wrong.

When you are in the car with your seatbelt off, if you exit the vehicle it's possible to toggle the seatbelt on while the exiting animation is still finishing. When this occurs, the next time you get in a car the HUD shows green seatbelt even though the seatbelt is off.

https://youtu.be/grf4cF2FOF4

Edit: Added video demo link

**Comment by zfbx** [comment]
This should be fixed in the newest commit - should be good to close
