### ISSUE TITLE
To complete the script, we must

### ISSUE THREAD

**Issue by darknight2590** [qbcore-framework/qb-hud#40]
1, add oxygen
2. add the engine case
3. add stamina
4. Converting the selection of colors through the hash, not the name of the color
5. and most importantly: The script should be more effective and the development of sending data to hud
6. Change the gray color as the background for the icons
in a new way
for example :
when using parachute 
It sends data to the script hud 
When the parachute is used, an icon appears on the screen, and when it stops using it, it sends data to close the icon
The script will be more effective
In this case, the icons will be used anywhere you want

RegisterCommand("test", function()
    local HudData = {
        {

        },
        },
    }
    exports["qb-hud"]:HudData (Data)
end)

**Comment by darknight2590** [comment]
This system is available on some servers

For example, you can add an icon when talking on the phone
Or entering a specific area in the server (a safe area)
Use a specific weapon
Or when using drugs, an icon appears
or drink alcohol

**Comment by GhzGarage** [comment]
What do you mean "to complete the script?" lol

**Comment by darknight2590** [comment]
my dreams
I hope the data pass will be added
For example, give programmers a chance
To add new features to the project
For example, I want to use a specific element
Show his status on hud

exports["qb-hud"]:SendEvent(There you can send, for example, data For example, when using a specific weapon, a new circle appears in the hud})

exports["qb-hud"]:SendEvent(Or when entering a certain area, a new circle appears in the hud})

exports["qb-hud"]:SendEvent(Or when drinking alcohol, for example})

The topic will be new and distinctive for the project
Through this idea, we will be able to pass data more interactively
From anywhere in the project and not in the script itself
I hope I explained the idea more clearly

**Comment by haitham1337** [comment]
I get what you mean
great idea
The script receives any data and converts it into circles
It will actually be very interactive
look at the picture
Here was used hud 
In a new circle as a counter for example
https://ibb.co/zSvb84W
