### ISSUE TITLE
Vehicle Hud speedometer , Fuel , seatbelt and light indicator overlay issues

### ISSUE THREAD

**Issue by AmanLathar** [qbcore-framework/qb-hud#46]
![image](https://user-images.githubusercontent.com/93133297/138692689-977cdc88-a5c1-44fb-977d-687938388c51.png)

tried many things but i cant make it work .

**Comment by ImLukeF** [comment]
no one is going to fix an issue for you when you are using custom resources. figure it out yourself and close this issue off
