### ISSUE TITLE
qb-hud does not display every time after a server restart (intermittent issue)

### ISSUE THREAD

**Issue by jawsoccer** [qbcore-framework/qb-hud#53]
After a server restart sometimes  the hud does not show up, map doesn't show in cars, no speedo nothing.

Running latest qb files with no edits to qb-hud

Running server artifact 4947

No server console errors

No F8 console errors

**Comment by jawsoccer** [comment]
**Update**

It seems that this may be a client sided issue (still testing as it doesn't always happen) Seems that sometime when a player joins the server after a restart their hud and phone do not work. Initially it seems that restarting the players game fixes the issue. Will update after completing more testing.

Moved to server artifact 4800 as this is what our live server running QB 2.0 is running. 

No server console errors

No F8 console errors

**Comment by mschiegg** [comment]
Same Probleme here, i don't have any ideas for a fix...
