### ISSUE TITLE
Hud doesn't load in

### ISSUE THREAD

**Issue by DeNiffo** [qbcore-framework/qb-hud#55]
When ever I add this hud into my server it doesn't show the map, general hud and carhud

**Comment by itzdaniel483** [comment]
yes I am also getting this issue

**Comment by BerkieBb** [comment]
The map and carhud should only show up in a car and the general hud only shows up if the values are different from their default value besides for the microphone input

**Comment by itzdaniel483** [comment]
> The map and carhud should only show up in a car and the general hud only shows up if the values are different from their default value besides for the microphone input

Unfortunately it doesn't load at all even when in own vehicle, tried stopping and restarting it. adding it to the top of the ensure list, nothing...

**Comment by BerkieBb** [comment]
Redownload and make sure that it starts after qb-core

**Comment by itzdaniel483** [comment]
Tried that still no luck

**Comment by itzdaniel483** [comment]
> Redownload and make sure that it starts after qb-core

Tried that still no luck :/
