### ISSUE TITLE
Vehicle Hud dont display speed over 250 

### ISSUE THREAD

**Issue by LiLNava** [qbcore-framework/qb-hud#60]
I use the 3.6 speed multiplier for KPH.

**Comment by googleoblivion** [comment]
Change the :max setting in index.html to your choosing.
`<q-circular-progress show-value :value="speed" class="text-white" size="60px" :thickness="0.15" color="white" track-color="grey-9" center-color="grey-10" :max="250"/>`

> :max="250"
