### ISSUE TITLE
Hud doensn't show up

### ISSUE THREAD

**Issue by SergioMMPeixoto** [qbcore-framework/qb-hud#67]
Hey, sometimes de HUD doesn't show up. Forcing the player to relog 1-5 times until it works.
No errors are displayed on the client, neither the server.
One-Sync is enabled.
When this happens all interactable blips disappear.
Also the phone doesn't open when this bug occurs but nothing else seems affected, Inventory and vMenu related menus are all working as intended.
Not all players online experience this at the same time. For some it works and for the others it doesn't.
I used the txAdmin recipe and have not changed anything in the configs.

Any clue to what might be happening?

Example of the bug:
![Untitled](https://user-images.githubusercontent.com/75185734/148805611-a4c499ee-21eb-44d2-9d16-2cd7d1a54052.png)

One-Sync and Game Version configuration:
![Untitled2](https://user-images.githubusercontent.com/75185734/148806280-d62ef394-f0f4-401b-83b3-f8944b4b5368.png)

**Comment by TapFreee** [comment]
i need help wwith it

**Comment by madmechanic187** [comment]
hi there i know this was last year but do you know how to fix this as im having the same issue with iceline phone wont come up no map or hud tried to update with new files from github still no joy 
on my home hosted server not had a issue
