### ISSUE TITLE
Player hp

### ISSUE THREAD

**Issue by kaviwi555** [qbcore-framework/qb-hud#71]
When relogging the player gets 75% HP as well as 75% armour

![image](https://user-images.githubusercontent.com/54584479/149474857-4418999f-a96b-4589-8eae-311bb7bd4608.png) (before relogging)

![image](https://user-images.githubusercontent.com/54584479/149474912-0a453049-3e7d-4c61-8e77-4fd34dfb3c4c.png)
 (after relogging)

**Comment by MonkeyWhisper** [comment]
Cannot duplicate this issue or find anything after debugging.
