### ISSUE TITLE
21:9 monitor's support

### ISSUE THREAD

**Issue by Klay4** [qbcore-framework/qb-hud#75]
Currently the hud isn't responsie for 21:9 monitor's.

Exemple (3440x1440)
https://i.imgur.com/pTaCYKs.png

**Comment by TylerA2** [comment]
Damn, you have one big ass screen my boy.

**Comment by Klay4** [comment]
> 

AHAHAHAHHA

**Comment by Klay4** [comment]
@Esplike AHAHAHAH

**Comment by nggcasey** [comment]
Yeah not ideal - Please fix for the ultrawide people

**Comment by loljoshie** [comment]
I'll be looking into this further tomorrow. The responsive CSS should be doing its job, however, it seems like it's not, thanks for reporting!
