### ISSUE TITLE
mini map

### ISSUE THREAD

**Issue by balcer64** [qbcore-framework/qb-hud#79]
![DPulHYpixjw](https://user-images.githubusercontent.com/22128071/149579628-7a534414-57c6-4882-85f3-f9a9512878d6.jpg) 
the is displayed incorrectly when selecting the round version

**Comment by loljoshie** [comment]
This should (HOPEFULLY) be resolved after the latest updates. If it's still borked let me know :') I'll keep this open for another 24 hours.

**Comment by balcer64** [comment]
> This should (HOPEFULLY) be resolved after the latest updates. If it's still borked let me know :') I'll keep this open for another 24 hours.

the circle appears only if you are in transport, if on foot the switch does not change
![1WK1rzGOiv0](https://user-images.githubusercontent.com/22128071/149638695-8792a1b0-2880-4c72-8b6a-6286b76bb46f.jpg)
![FypKI0iNOiM](https://user-images.githubusercontent.com/22128071/149638697-6755f8a1-0fdb-4166-ae80-16c1831d8727.jpg)

the file was updated 20 minutes ago

**Comment by balcer64** [comment]
the minimap is very low, the screenshots are above the 1920 x 1080 screen, this screenshot is 1380 x768
![screenshot101](https://user-images.githubusercontent.com/22128071/149638848-e0978776-6796-4b2b-bb60-d8c3f6e9bb82.png)

**Comment by loljoshie** [comment]
Should be fixed! Reopen this if it's still buggy. Thanks for the report!
