### ISSUE TITLE
compass issue

### ISSUE THREAD

**Issue by ayushabhinav-dev** [qbcore-framework/qb-hud#83]
after adding lj compass also we are not able to turn off and on compass

**Comment by loljoshie** [comment]
I tested this myself, and it does indeed work. Make sure you remove the -main from lj-compass file after downloading it because the NUICallback will not trigger otherwise

**Comment by CTRP-Framework** [comment]
i have tried but same result

**Comment by ayushabhinav-dev** [comment]
ok let me check

**Comment by ayushabhinav-dev** [comment]
thankyou its done i missed last s in compass
