### ISSUE TITLE
Dev mode

### ISSUE THREAD

**Issue by ayushabhinav-dev** [qbcore-framework/qb-hud#84]
there is no such event in qb-adminmenu as "qb-admin:client:ToggleDevmode"

**Comment by loljoshie** [comment]
Just sent in a PR to qb-adminmenu, I completely forgot about this feature while getting everything over to the framework! Thanks!!

**Comment by ayushabhinav-dev** [comment]
Bro i checked your pull request that Invinciblety thing is already as gode mode 

```local godmode = false
menu_button8:On('change', function(item, newValue, oldValue)
    godmode = not godmode

    if godmode then
        while godmode do
            Wait(0)
            SetPlayerInvincible(PlayerId(), true)
        end
        SetPlayerInvincible(PlayerId(), false)
    end
end)```

No need to add same thing please check that

thankyou

**Comment by ayushabhinav-dev** [comment]
[
![image](https://user-images.githubusercontent.com/93464022/149635302-29e33e70-59cc-4632-aab9-b85146803a52.png)
](url) Check this i have done im my server

**Comment by loljoshie** [comment]
Please, don't reply in both resources regarding the same topic. Either keep the discussion in qb-adminmenu or qb-hud and I've already responded to your comment on qb-adminmenu, thanks!

**Comment by ayushabhinav-dev** [comment]
OK SORRY FOR THAT THANKYOU
