### ISSUE TITLE
minimap twitching

### ISSUE THREAD

**Issue by YazIV** [qbcore-framework/qb-hud#85]
https://medal.tv/games/gta-v/clips/7PLuGw12R-XhV/d1337Es0TPzS?invite=cr-MSxoVlMsMjc0MjcwOTIs

it keeps twitching for some reason its so annoying

**Comment by MonkeyWhisper** [comment]
This happens when you restart the resource.

**Comment by loljoshie** [comment]
Should be fixed! Thanks for reporting!
