### ISSUE TITLE
[Bug] Circle map

### ISSUE THREAD

**Issue by KingRyuShin** [qbcore-framework/qb-hud#88]
When you select circle map for default map, once you log into your server, the map is square, you have to go back to settings and select circle map with the slider for it to take effect.

**Comment by MonkeyWhisper** [comment]
This is accurate, a lot of people have been reporting this and I have tested it myself and have experience this.

**Comment by loljoshie** [comment]
Should be fixed! Reopen this if it's still buggy. Thanks for the report!
