### ISSUE TITLE
seatbelt/harness

### ISSUE THREAD

**Issue by KenanDK666** [qbcore-framework/qb-hud#92]
I have an issue with seatbelt and harness, when i press "b" to put my seatbelt on the orange seatbelt icon don't disappear and i don't have to take off the seatbelt to get out of the car, and i still get thrown out of the window when i crash.

when i use the harness the orange icon disappears and  im basically locked in the car even if i reuse the harness to remove it so i have to park the car to get out of it.

didn't have that issue with the seatbelt before when it was lj-hud, and i seldom use the race harness since its an item you have to use and  it bugs out for me.

**Comment by loljoshie** [comment]
Should be fixed! Thanks for reporting!
